apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-app
  labels:
    app: hazelcast
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 5701
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /config
              name: hazelcast
      volumes:
        - name: hazelcast-config
          configMap:
            name: hazelcast-config
            items:
              - key: hazelcast.yaml
                path: hazelcast.yaml
